FirstCommit(FirstUpdate)
mkelshapik/MyCollections pull request #1
Opened 2021-09-02 17:27 UTC by mkelshapik

2021-09-03 02:01 UTC, romiope requested changes
Please fix issues and send for review again

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayList.java
> +            t = (T[]) new Object[temp.length + INITIAL_CAPACITY];
you increased array but forget to increase capacity

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayList.java
> +                t = (T[]) new Object[temp.length + INITIAL_CAPACITY];
same as previous

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayList.java
> +            size--;
you can do this in one place

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayList.java
> +        if (size == 0) {
you can just `return size == 0;`

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayList.java
> +            if (t[i].equals(o) && t[i].hashCode() == o.hashCode()){
why do you need this `&& t[i].hashCode() == o.hashCode()` ?

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayList.java
> +    public Object set(int index, Object element) {
why does this method return object it set?

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayList.java
> +            if (t[i].equals(o) && t[i].hashCode() == o.hashCode()){
why do you need this ? `&& t[i].hashCode() == o.hashCode()`

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayList.java
> +        throw new NotImplementedException();
please implement this to be able to traverse list in:
`for (T e : list) {
}`

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayList.java
> +        throw new NotImplementedException();
this is easy to implement, just return your array

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayList.java
> +        throw new NotImplementedException();
please implement this as well

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayListTest.java
> +    void checkAddAndConstructor(){
where is a check in the test?

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayListTest.java
> +    MyArrayList<Integer> myArrayList = new MyArrayList<>();
you should use:
`List<Integer> myArrayList = new MyArrayList<>();` instead

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayListTest.java
> +    void contains() {
where is a code?

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayListTest.java
> +        assertEquals(5, myArrayList.set(0, 5));
what do you check here?

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyArrayListTest.java
> +    void indexOf() {
please add more checks. for example when you remove items from front, does it shift all elements? indexes in that case has to be different.

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyLinkedList.java
> +            size++;
what is this? why it is here?

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyLinkedList.java
> +    public boolean add(Object o) {
this method should increase size

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyLinkedList.java
> +    public void add(int index, Object element) {
this has to take E, not Object

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyLinkedList.java
> +    public boolean add(Object o) {
should be E instead of Object

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyLinkedList.java
> +    public boolean contains(Object o) {
should use E

2021-09-03 02:01 UTC, r-zaiarnyi commented on src/MyLinkedListTest.java
> +class MyLinkedListTest {
this test should be the same as test of ArrayList

2021-09-03 02:01 UTC, romiope commented on src/MyStackTest.java
> +    void isEmpty() {
also add some test which check if `isEmpty() == false` after added elements and true after removal

2021-09-03 17:11 UTC, mkelshapik commented on src/MyArrayList.java
> +            t = (T[]) new Object[temp.length + INITIAL_CAPACITY];
corrected

2021-09-03 17:11 UTC, mkelshapik commented on src/MyArrayList.java
> +                t = (T[]) new Object[temp.length + INITIAL_CAPACITY];
corrected

2021-09-03 17:11 UTC, mkelshapik commented on src/MyArrayList.java
> +            size--;
corrected

2021-09-03 17:11 UTC, mkelshapik commented on src/MyArrayList.java
> +        if (size == 0) {
corrected

2021-09-03 17:11 UTC, mkelshapik commented on src/MyArrayList.java
> +            if (t[i].equals(o) && t[i].hashCode() == o.hashCode()){
corrected

2021-09-03 17:14 UTC, mkelshapik commented on src/MyArrayList.java
> +            if (t[i].equals(o) && t[i].hashCode() == o.hashCode()){
corrected

2021-09-03 17:19 UTC, mkelshapik commented on src/MyArrayList.java
> +    public Object set(int index, Object element) {
corrected

2021-09-03 17:24 UTC, mkelshapik commented on src/MyArrayList.java
> +        throw new NotImplementedException();
ready

2021-09-07 09:28 UTC, mkelshapik commented on src/MyArrayList.java
> +        throw new NotImplementedException();
Check

2021-09-07 09:29 UTC, mkelshapik commented on src/MyArrayList.java
> +        throw new NotImplementedException();
Check

2021-09-07 09:32 UTC, mkelshapik commented on src/MyArrayListTest.java
> +    void checkAddAndConstructor(){
Check

2021-09-07 09:32 UTC, mkelshapik commented on src/MyArrayListTest.java
> +    MyArrayList<Integer> myArrayList = new MyArrayList<>();
Check

2021-09-07 09:34 UTC, mkelshapik commented on src/MyArrayListTest.java
> +    void contains() {
Check

2021-09-07 09:37 UTC, mkelshapik commented on src/MyArrayListTest.java
> +        assertEquals(5, myArrayList.set(0, 5));
Check

2021-09-07 12:34 UTC, mkelshapik commented on src/MyArrayListTest.java
> +    void indexOf() {
Check

2021-09-13 18:27 UTC, mkelshapik commented on src/MyLinkedList.java
> +            size++;
Corrected

2021-09-13 18:33 UTC, mkelshapik commented on src/MyLinkedList.java
> +    public void add(int index, Object element) {
annotation does not allow me do it

2021-09-13 18:34 UTC, mkelshapik commented on src/MyLinkedList.java
> +    public boolean add(Object o) {
the same above

2021-09-13 18:34 UTC, mkelshapik commented on src/MyLinkedList.java
> +    public boolean contains(Object o) {
))

2021-10-22 09:10 UTC, merged